name: Set Up Env
description: Install Zig
runs:
  using: composite
  steps:
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.0
    - uses: extractions/setup-just@v2
    - name: Check Zig ENV
      shell: bash
      run: |
        zig env
    - uses: actions/setup-node@v4
      with:
        node-version: 22
